### ISSUE TITLE
ojph_compress support for uppercase file extensions

### ISSUE THREAD

**Issue by michaeldsmith** [aous72/OpenJPH#101]
ojph_compress does not seem to support input files with upper case extension "RAW" and seems to only support only lowercase "raw" file extension.

For example, this does not work :

`ojph_compress -dims "{256,1024}" -num_comps 1 -signed true -bit_depth 16 -downsamp "{1,1}" -reversible true -i ../source/NM1_256x1024_16b.RAW -o ../compressed/NM1_256x1024_16b.openjph.j2c`

and gives error message:

`ojph error 0x01000041 at ojph_compress.cpp:842: unknown input file extension; only pgm, ppm, tif(f), or raw(yuv) are supported
`
   
while this does work and gives no error message:

`ojph_compress -dims "{256,1024}" -num_comps 1 -signed true -bit_depth 16 -downsamp "{1,1}" -reversible true -i ../source/NM1_256x1024_16b.raw -o ../compressed/NM1_256x1024_16b.openjph.j2c`

**Comment by aous72** [comment]
This has been addressed for ojph_compress and ojph_expand.  Thank you Mike.
