### ISSUE TITLE
openjph decompression fails 

### ISSUE THREAD

**Issue by madhub** [aous72/OpenJPH#107]
Trying to use the **openjph** to decompress the **HTJ2K** (image attached inside the demo.zip file) . Output of openjph **ojph_expand.exe** is not proper. Same data is  decompressed using **kakadu decompression utility,** it shows up properly in the viewer .

Viewer used : [ImageJ](https://imagej.net/ij/index.html) Viewer 
![image](https://github.com/aous72/OpenJPH/assets/8907962/a17e9ba3-ef1d-4fc6-99ac-a6a9a2cec97d)

Decoding using OpenJPH utility
```shell
ojph_expand.exe -i demo.j2c -o demo.raw
```
Decoding using kakadu utility - **This works** 
```shell
kdu_expand.exe -i demo.j2c -o demo.raw
```
try opening raw image attached in the zip file. Image details has below
**Width=512, Height=512, BitDepth=8, Samples Per Pixel = 1.**

[demo.zip](https://github.com/aous72/OpenJPH/files/12260186/demo.zip)

**Comment by aous72** [comment]
Thank you @madhub for discovering this bug.
This should fix this issues.
Please give it another try and see how it goes.

pgm, yuv, and tiff should not be affected by this bug.

**Comment by madhub** [comment]
> Thank you @madhub for discovering this bug. This should fix this issues. Please give it another try and see how it goes.
> 
> pgm, yuv, and tiff should not be affected by this bug.

Yes it fixes the issue. Thanks for the quick response
