### ISSUE TITLE
Build should not fail if SIMD optimizations are enabled and your CPU doesn't support them

### ISSUE THREAD

**Issue by chafey** [aous72/OpenJPH#111]
The build fails on my Apple M1 MacBook Pro unless I explicitly turn OJPH_DISABLE_INTEL_SIMD OFF.  This is not only inconvenient, but causes problem with using in upstream projects that may or may not know the target architecture.  It would be much better if:
1) CMAKE variable could be used to disable optimizations
2) The right optimizations for the target CPU are automatically enabled

Perhaps this might help: https://github.com/scivision/cmake-cpu-detect

**Comment by aous72** [comment]
Hi Chris,

I agree that I need a proper support for ARM, and possibly other platforms.

Thank you for the links; it is very useful.

Kind regards,
Aous.

**Comment by aous72** [comment]
Please reopen this issue, if the new version has an issue.
Thank you for your help.
Aous
