### ISSUE TITLE
Missing comment type in file header comment box

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#12]
Type should go in the first two bytes of the box data:

0 for binary comment
1 for IS 8859-15:1999 latin comment

So, you want to set type to 1.

**Comment by aous72** [comment]
This is my mistake. It has to be fixed.

**Comment by aous72** [comment]
Fixed.

**Comment by aous72** [comment]
Thank you for discovering this. Somehow I missed it.

**Comment by boxerab** [comment]
My pleasure. By the way, if you put `closes #12` in your commit comment, then Github will automatically close the issue.

**Comment by aous72** [comment]
This is useful to know.  Thank you for letting me know.
