### ISSUE TITLE
Tests fails to pass in version 0.10.4

### ISSUE THREAD

**Issue by dbermond** [aous72/OpenJPH#127]
The tests are failing to pass for me in version 0.10.4. Only tests 1 and 2 passes out of 77 total tests. CMake tests log: [LastTest.log](https://github.com/aous72/OpenJPH/files/14208216/LastTest.log).

Tests are passing fine in version 0.10.3.

A git bisect shows the offending commit as being 4d50eb7c75e0bc297400b48a3e6ab65bbb2a4ef4.

Commands used:

```
$ cmake -B build -S 'OpenJPH-0.10.4' \
        -G 'Unix Makefiles' \
        -DCMAKE_BUILD_TYPE:STRING='None' \
        -DCMAKE_INSTALL_PREFIX:PATH='/usr' \
        -DOJPH_ENABLE_INTEL_AVX512:BOOL='OFF' \
        -DOJPH_BUILD_TESTS:BOOL='ON' \
        -Wno-dev
$ cmake --build build
$ ctest --test-dir build --output-on-failure
```

System Information:
- OS: Arch Linux
- CMake: 3.28.3
- Compiler: gcc 13.2.1
- libtiff: 4.6.0

**Comment by aous72** [comment]
Hi Daniel,

Thank you for letting me know.
Commit [8f5924d](https://github.com/aous72/OpenJPH/commit/8f5924d65f6a65dc2e3c4f3083b6c83675138ac2) should address this issue.
I also took the chance to improve installation, by removing unnecessary gtest files from installation.

There is another issue to fix, before I release this commit into version 0.10.5

Thank you.
Kind regards,
Aous

**Comment by dbermond** [comment]
I can confirm that this is now fixed in the current git master.

Thank you for fixing this!
