### ISSUE TITLE
  #pragma intrinsic is MSVC specific

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#13]
This is MSVC specific, so it could be protected by an #ifdef:

```
#ifdef _MSC_VER

#endif
```

**Comment by aous72** [comment]
I did not understand what you mean.  
I used in one place to detect visual studio.  
My idea is that this is useful to detect windows/visual studio.

**Comment by boxerab** [comment]
Thanks, I'm sorry for not being clearer, and not sure if I understand your meaning. This pragma causes a warning for non-MSVC compilers. To suppress the warning, it can be placed inside an #ifdef:

```
#ifdef _MSC_VER
#pgrama intrinsic
#endif
 ```

**Comment by aous72** [comment]
Addressed this issue in the last commit
