### ISSUE TITLE
Encode 115x25的YUV444 picture，There is serious distortion.

### ISSUE THREAD

**Issue by xuws2016** [aous72/OpenJPH#132]
The following is a coded input image：
![TestServer](https://github.com/aous72/OpenJPH/assets/131847317/c693df41-7c34-4a7f-a66a-335087ba160a)
The following is a coded output image：
![TestServerOut](https://github.com/aous72/OpenJPH/assets/131847317/8ef1c16e-4a5c-40fd-94b0-d44fb4c500f3)

**Comment by aous72** [comment]
Hi There,

There was a bug in the wavelet transform that I fixed in version 0.10.4.  Are you using 0.10.4 or 0.10.5?
Also, could you give the command line arguments please, or was this obtained with the default options?

I will look at this later today.

Cheers,
Aous.

**Comment by aous72** [comment]
Yes it was that bug.

```
git pull
git checkout 0.10.5
```

Cheers,
Aous.

**Comment by xuws2016** [comment]
thanks

**Comment by aous72** [comment]
I think this has been solved.  I am closing it. Please open it or open another one if the problem returns.
