### ISSUE TITLE
-fexceptions is missing when configuring the wasm build

### ISSUE THREAD

**Issue by palemieux** [aous72/OpenJPH#147]
`-fexceptions` is necessary otherwise [exceptions that are thrown in the code are not caught within the code](https://emscripten.org/docs/porting/exceptions.html?highlight=fexceptions).

https://github.com/aous72/OpenJPH/blob/46da3dc409f9ffb82045610a1f7cfe99a165ad14/subprojects/js/CMakeLists.txt#L12

**Comment by aous72** [comment]
Hi Pierre,

Thank you for putting this.  It is an oversight on my part.  
I have the flag for the library, but forgot to add it here.
I will fix it soon.

Kind regards,
Aous.

**Comment by aous72** [comment]
This issue was addressed in release 0.15.0.
If there are any issues, please reopen this issue.
