### ISSUE TITLE
CPF warning message should be demoted to info message or eliminated

### ISSUE THREAD

**Issue by michaeldsmith** [aous72/OpenJPH#15]
Decoding a Part-15 J2C file containing a CPF marker segment (Corresponding Profile) issues a "warning" 

`ojph warning 0x00030001 at ojph_codestream.cpp:430: CPF is not supported yet`

rather than a less severe "info" message.  This is not a useful warning, to users unfamiliar with CPF, it makes it sound like CPF is required but not supported.  When in fact CPF is pretty much useless to a HT decoder.   Perhaps this should be changed to an info message like

`ojph info 0x00030001 at ojph_codestream.cpp:430: Skipping unknown CPF marker segment `

If there is no `info `class of message, this whole message could be removed as its not really important to a decoder.  I think CPF could be more important to a Part-15 to Part-1 transcoder.

Here is a dropbox link to a Lossy Part-15 J2C file containing a CPF marker

[https://www.dropbox.com/s/aaq5jipf90vg514/mer_shrt_23976_vdm_sdr_rec709_g24_3840x2160_20170913.ht.00090000.j2c?dl=0](https://www.dropbox.com/s/aaq5jipf90vg514/mer_shrt_23976_vdm_sdr_rec709_g24_3840x2160_20170913.ht.00090000.j2c?dl=0)

**Comment by aous72** [comment]
I agree.  This requires careful investigation of each warning message, to demote some of them.

Thank you Mike.

**Comment by michaeldsmith** [comment]
I think the following markers segments could be skipped without any effect on normal decoding (assuming the decoding process is not decoding a bitstream with bit errors or erasures)
```
COM 
TLM 
PRF 
PLM 
PLT 
CPF 
SOP 
EPH
``` 

The `CRG` marker segment could also be skipped, but it is possible the information in the CRG marker could help with post-decode reconstruction of R'G'B' from Y'CbCr that could be important in some applications.  For example the phase of the reconstruction filters should be changed depending on whether the Cb and Cr samples are vertically/horizontally co-sited or interstitial with the luma Y' sample.  In professional video applications where this is expected to be important, there is usually some higher level system or essence description that carries this information.  The co-sited/interstitial arrangement is usually specified by the video standard itself, for example ITU-R BT.709 has one arrangement, ITU-R BT.2020 has a different arrangement, and the arrangement typically varies with interlace versus progressive sampling structures as well.

**Comment by aous72** [comment]
Thank you Mike for this good suggestion.  I will work on this and push it in the next few days.

Happy new year.

**Comment by aous72** [comment]
I think I have addressed this issue, and I am closing it.  Please reopen this issue if I made a mistake or missed anything.
