### ISSUE TITLE
Installation causes KDE Plasma 6 to crash

### ISSUE THREAD

**Issue by gbcox** [aous72/OpenJPH#152]
Not sure why, whether this is a KDE bug  or some inherent incompatibility.  Problem does not seem to occur with GNOME.
Reported here with dumps:
https://bugzilla.redhat.com/show_bug.cgi?id=2307795

**Comment by aous72** [comment]
Hi Gerald,

Thank you for putting this in.
I am happy to help, but I am not sure what to do to discover the problem?

Is it possible that there is a binary compatibility issue between libheif-jphenc.so and libopenjph? libheif-jphenc.so expecting different ABI from libopenjph.so?  Perhaps, GNOME expects the correct ABI.

Kind regards,
Aous.

**Comment by gbcox** [comment]
Hello Aous, Thanks for the quick response.  I created a bug upstream with KDE here:
https://bugs.kde.org/show_bug.cgi?id=492220

Perhaps they can take a look and comment and hopefully it will be helpful.

**Comment by gbcox** [comment]
Closing.  Not a bug.  Issue do to compiler options specified.
