### ISSUE TITLE
Usage question -- Getting access to the in-memory representation of the compressed data

### ISSUE THREAD

**Issue by hmaarrfk** [aous72/OpenJPH#164]
Happy new year! 

Thank you for the great work! I've been testing this library and I find it quite compelling.

I actually managed to write some python wrappers to help me better benchmark things when compared to other compression options.

I was wondering if there was a way to get access to the "binary data" that we must dump to a tiff in order to make this "compliant" with OpenJPEG'ed compressed TIFF page.

I know you are working with openjpeg to do this https://github.com/uclouvain/openjpeg/issues/1487

however, while waiting, is there a way to access the "compressed data" and the "required headers" as data pointers for us to write to a file (or memory bufffer) ourselves?

I hope this question makes sense.

Best,

Mark

**Comment by hmaarrfk** [comment]
For example, for the "decompression path" i found the `line` interface of `codestream.pull`

https://github.com/ramonaoptics/ojph/blob/main/ojph/_imread.py#L96

**Comment by aous72** [comment]
Hi Mark,

Happy holiday season!
Glad you found the library useful.

I am a bit confused about the question.
I think you are asking if you can compress an image into a memory file.
The answer is yes. You can use ```ojph::mem_outfile```
https://github.com/aous72/OpenJPH/blob/1b20dbcdb47b82c8eb1028da396e155088309217/src/core/common/ojph_file.h#L126
Then you use the created object as an output file for compression, using it in ```codestream.write_headers()```.
Then you can access the compressed data from this memory file, copy it somewhere else, or write it to a file.

Alternatively, you can use develop a derived class/object from ```ojph::outfile_base```, and use it, where ```ojph::mem_outfile``` serves as an example implementation, as Chris Hafey is doing in https://github.com/chafey/openjphjs/blob/master/src/EncodedBuffer.hpp

Does that answer the question?  please let me know.

**Comment by hmaarrfk** [comment]
I think this answers my question. I'll have to study it in a bit more depth. I had a hunch that this is what I was supposed to look for but I wasn't sure.

As a followup question. do you know if this is "in memory file" is what I need to dump to a TIFF page in order for readers to open it correctly?

Do you know of a TIFF reader that can open OpenJPEG files that I could test my writer against?

**Comment by aous72** [comment]
I am not familiar with TIFF pages, and TIFF in general.
I am sorry I cannot help in this regard.

**Comment by hmaarrfk** [comment]
Alright, thank you so much already, i'll close this and maybe reopen or get in touch again if I have new questions.

Happy new year!!!

**Comment by hmaarrfk** [comment]
Thx for the pointers. I finally got around to it.

I have a super hackjob of an implementation done in
https://github.com/ramonaoptics/ojph/pull/4
