### ISSUE TITLE
A suspicious line of code

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#19]
From   `param_qcd`

```
            base_delta = 1.0f /
              (1 << (siz.get_bit_depth(0) + siz.is_signed(0)));
```

Did you intend to add an `int` and a `boolean` ?

**Comment by aous72** [comment]
Hi Aaron,

Yes. What are you thoughts on this?

Boolean will be converted to 1 for true and 0 for false.

**Comment by boxerab** [comment]
Thanks, just wanted to check this :)
