### ISSUE TITLE
test.j2c used in web browser demo

### ISSUE THREAD

**Issue by chafey** [aous72/OpenJPH#2]
I noticed that test.j2c used in the web browser demo is 360,586 bytes long.  This would be quite impressive if it is lossless, but I don't know how to look at the j2c header and there is no source image to reproduce.  It would be nice if you could add the input/source image you used to feed the compressor and the command line arguments you used to generate test.j2c.  Even better would be to check in the original lena512color.tiff with a script to generate test.j2c.  In addition to this, it would be nice to have a few input.source images of different types with scripts to convert them (grayscale 16 bit is of specific interest to me).

**Comment by aous72** [comment]
The test.j2c file employs with high-quality lossy compression.  For lossless compression, the size would be around 471079.  JPH is less efficient than J2K by a small amount, in the order of, I think, 5-7% (see the white paper), but it has significantly lower computational complexity.

I forgot what command line was used to obtain the lena image, but this command
    ../bin/ojph_compress -i lena.ppm -o test.j2c -num_decomps 5
should produce largely similar results.  To obtain a lossless version of it, use
    ../bin/ojph_compress -i lena.ppm -o test.j2c -num_decomps 5 -reversible true

I agree that it can be useful to provide more usage examples than the two examples provided in README.MD; however, providing images is beyond the scope of the work.  Images have their associated licences, and they should not be very large; perhaps you can help with providing images.

Cheers,
Aous.

**Comment by chafey** [comment]
I can help with images and will keep them small.  How about a new folder at the root called /images that has the source images, j2c result images and a script to run ojph_compress with the right settings to generate the j2c result images?

**Comment by aous72** [comment]
This seems like a good idea. Please provide these images.  I hope there are no licensing issues, and the images can be provided under the 2-clause BSD license.

Thank you Chris.

**Comment by chafey** [comment]
I have some pictures I own so will use those - no licensing issues :)

**Comment by chafey** [comment]
I extracted the RAW frames from some [freely available DICOM images](ftp://medical.nema.org/MEDICAL/Dicom/DataSets/WG04) and converted them to J2C here: 

https://github.com/chafey/openjphjs/tree/master/test/fixtures/j2c

Feel free to use them as you see fit.  I don't know what license (if any) these were released under, but they were made available for the public to use
