### ISSUE TITLE
Suggest documenting typical color subsampling

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [aous72/OpenJPH#22]
I think it would be handy for documentation to list how standard color subsamplings (4:2:2, 4:2:0, etc.) can be expressed with  -downsamp

**Comment by aous72** [comment]
Thank you for this suggestion.

I will do that.

The example for 4:2:0 is already there.  
I need to put an example for 4:2:2, and I guess provide more documentation.

**Comment by NEOAdvancedTechnology** [comment]
Thanks!

**Comment by aous72** [comment]
For 422, use
-downsamp \\\{1,1\\\},\\\{2,1\\\}
This is downsampled in the x-direction by 2.

**Comment by NEOAdvancedTechnology** [comment]
Great, thanks!
