### ISSUE TITLE
ojph_expand .ppm file output not quite right as per ffmpeg

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [aous72/OpenJPH#23]
`~/OpenJPH/bin$ ./ojph_expand -i test.j2c -o test_out.ppm
Elapsed time = 0.112212`

`~/OpenJPH/bin$ ffprobe test_out.ppm`

```
ffprobe version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
test_out.ppm: Invalid data found when processing input
```

**Comment by aous72** [comment]
Thank you for reporting this.  

I am not familiar with ffprobe.

What commandline was used to generate test.j2c? and if possible, can I have access to test.j2c?

**Comment by NEOAdvancedTechnology** [comment]
ffprobe is an ffmpeg app that gathers information from multimedia streams and prints it in human- and machine-readable fashion.  https://ffmpeg.org/ffprobe.html 

I made an artificial test image "bars.ppm", with HTJ2K encode file "bars.j2c", and decoded file "bars_out.ppm".  ffprobe still says `bars_out.ppm: Invalid data found when processing input`

The files are in this repository: [https://github.com/NEOAdvancedTechnology/htj2k_test_files](https://github.com/NEOAdvancedTechnology/htj2k_test_files)

**Comment by aous72** [comment]
Thank you for the files.  I had a look.

Next is a speculation.

I think this might be a bug in ffprobe.  
I can open both bars.ppm and bars_out.ppm with IrfanView64 without any issues.

I think the difference that is causing the issue is related to how white spaces are interpreted.   

bars.ppm:
ASCII code: 50 36 **_0a_** 31 32 38 30 20 37 32 30 **_0a_** 32 35 35 0a  
ASCII char: P6.1280 720.255.
 
bars_out.ppm:
ASCII code: 50 36 **_20_** 31 32 38 30 20 37 32 30 **_20_** 32 35 35 0a  
ASCII char: P6 1280 720 255.

Note the whitespace between P6 and 1280, and then again between 720 and 255.  bars_out.ppm is using a space (0x20) while bars.ppm is using \newline (0x0a).

According to this document:
http://netpbm.sourceforge.net/doc/ppm.html
Any white space should be alright.

It is very easy to modify from my side, but ffprobe should have better support for the ppm format.

**Comment by NEOAdvancedTechnology** [comment]
Indeed, I converted bars_out.ppm using ImageMagick to another ppm file, and it also has the 0x0a "." after the P6, which ffprobe/ffmpeg seems too be happier with.

**Comment by aous72** [comment]
I forgot to send this.

The version I have of ffprobe does not have this issue.

    ffprobe version 4.1 Copyright (c) 2007-2018 the FFmpeg developers
      built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
      configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gpl --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-opencl --enable-videotoolbox
      libavutil      56. 22.100 / 56. 22.100
      libavcodec     58. 35.100 / 58. 35.100
      libavformat    58. 20.100 / 58. 20.100
      libavdevice    58.  5.100 / 58.  5.100
      libavfilter     7. 40.101 /  7. 40.101
      libavresample   4.  0.  0 /  4.  0.  0
      libswscale      5.  3.100 /  5.  3.100
      libswresample   3.  3.100 /  3.  3.100
      libpostproc    55.  3.100 / 55.  3.100
    Input #0, image2, from 'bars_out.ppm':
      Duration: 00:00:00.04, start: 0.000000, bitrate: 552963 kb/s
        Stream #0:0: Video: ppm, rgb24, 1280x720, 25 tbr, 25 tbn, 25 tbc

In any case, I am modifying the code to generate a header acceptable to the older version of ffprobe you are using.  I think this is better.
