### ISSUE TITLE
Bug in lossy quantization step size ?

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#24]
According to the standard, this is what I get as the formula for irrev step size:

```
    float param_qcd::irrev_get_delta(int resolution, int subband) const
    {
      assert((resolution == 0 && subband == 0) ||
             (resolution <= num_decomps && subband > 0 && subband<4));
      assert((Sqcd & 0x1F) == 2);
      float gain[] = { 0.0f, 1.0f, 1.0f, 2.0f };

      int idx = ojph_max(resolution - 1, 0) * 3 + subband;
      int exp = u16_SPqcd[idx] >> 11;
  	  return (float) (((1.0 + (u16_SPqcd[idx] & 0x7FF)/ 2048.0)
  			* pow(2.0, (int32_t) (gain[subband] - exp))));

    }
```

So, the only difference seems to be that the current code has
` (1 + mantissa)/2048.0 `
rather than
`1.0f + mantissa/2048.0`

Or am I missing something ?

**Comment by aous72** [comment]
Hi Aaron,

I see that you are still looking into my code.  This is good to discover bugs.

The code I have is no different to the formula you have put.

I am doing (2048 + (u16_SPqcd[idx] & 0x7FF)) / 2048 == 1 + (u16_SPqcd[idx] & 0x7FF) / 2048.

Does this answer your question?

Cheers,
Aous.

**Comment by boxerab** [comment]
Thanks, Aous, yes, the formulae are the same.
