### ISSUE TITLE
Question about sqrt_energy_gains

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#26]
Hi Aous,
Hope all is well. I am curious: are the `sqrt_energy_gains` arrays related to the wavelet norms for the different sub-bands? i.e. can the HH sub-band of the first decomposition be calculated from the energy gains ?
Thanks,
Aaron

**Comment by aous72** [comment]
Hi Aaron,

So far, all is well.  I hope you and family are all well in these trying times.

You are correct, these are the 1D synthesis  ℓ<sub>2</sub> norms (or the square root of the synthesis energy gain).

The gain_9x7_l starts with sequence of 1 (a delta), and then convolving by the low-pass (g0) of the synthesis filters and upsampling, repeatedly the number of decomposition levels.
The gain_9x7_h starts with the high-pass (g1) synthesis filter, upsampling, and then convolving by low-pass (g0) of the synthesis filters and upsampling, repeatedly the number of decomposition levels - 1.
The difference is only in the first step.  This is possible when the 2D wavelet transform is separable, obtained from the product of two 1D filters, as is the case with J2K.

The norm for the HH subband is the product of gain_9x7_h[0] * gain_9x7_h[0] = 1.4425 * 1.4425.

I hope I made no inadvertent mistakes.

Stay safe.

Kind regards,
Aous.

**Comment by boxerab** [comment]
Thanks, Aous, glad to hear you're well. Here in Canada, we haven't been hit too badly by the outbreak, so far. But it is still quite stressful.

Thanks very much for the explanation of how the energy calculations work. Much appreciated !

Likewise, stay safe and Best Wishes,
Aaron
