### ISSUE TITLE
Source Code Documentation

### ISSUE THREAD

**Issue by chafey** [aous72/OpenJPH#3]
I would like to make sure that the code I contribute is documented and am unsure what documentation guidelines are being followed.  I have used doxygen style in the past and would prefer that if there is no preference.  If there is a preference, can we add a link to the style in the documentation somewhere?

**Comment by aous72** [comment]
We definitely need this. 

I think a lot of people are using doxygen, and I am all for it.

You are right, we need a style.  Anything particular style you suggest?

**Comment by chafey** [comment]
I will research options for C++ coding styles - hopefully I can find something someone else is using (e.g. Google's C++ guidelines).  We will likely need to modify it somewhat given your desire to avoid STL (which most coding standards will embrace)

**Comment by aous72** [comment]
I thought you had one in mind. Don't worry, I will cook up something.

Cheers,
Aous
