### ISSUE TITLE
Suggestion: add support for partial bitstream decoding

### ISSUE THREAD

**Issue by chafey** [aous72/OpenJPH#36]
It would be useful to be able to decode a partial bitstream.  For images encoded in resolution order (RLCP, RPCL), this would allow sub resolutions to be decoded from a partial bitstream enabling a client to display a thumbnail for an image without having to download the entire image.  To accomplish this, a few things would be needed:
1) Add a function to codestream that returns the actual resolution at a given decomposition level.  
2) Add an optional parameter to codestream.pull() would need to take the decomposition level desired (0 - num_decompositions) where 0 is the base resolution.  pull() would return a line with the number of elements in the width at that decomposition level (matching #1 above).
3) Make the codestream parser resilient to partial bitstreams.  By default it would return an error like it does today, but we could add a flag that would cause it to parse as much as it can but not fail.  It could even store the highest full decomposition level it was able to parse somehow.

This functionality would not be available with non R* progression orders.

Related to this is enhancing the encoder to produce information about the size/location of each decomposition level in the encoded bitstream.  That way a client could read the exact number of bytes needed to produce a specific decomposition level.  This may also help 3 above if it is messy/difficult to make the decoder resilient to partial bitstream of arbitrary lengths
 
I am happy to do the work, but don't want to do it if its not wanted or rejected

**Comment by aous72** [comment]
We can always discuss.  There are many things I am not very sure how to go about.  I have my own vision of how things should proceed.  Of course you also have yours.

Adding the functionality for any progression order is useful for ojph_expand, where the end-user might choose how many resolutions to skip.

For download applications, progression orders other than those starting with R are not useful and should be avoided as you are well aware.

I think I know what to do regarding lengths.

Thank you Chris.

Kind regards,
Aous.

**Comment by chafey** [comment]
Regarding vision - I have no interest in maintaining my own fork, I am hoping to collaborate with you and figure out the best approach.  We both come from different backgrounds, combining our knowledge should produce better results than doing things independently
