### ISSUE TITLE
A few more warnings :)

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#37]
Hi Aous,
Hope all is well, and thanks for fixing those warnings. My compiler is much happier.
However, there are still a number of warnings that should probably be looked at:

You can see them [here](https://my.cdash.org/viewBuildError.php?type=1&buildid=1824284)

I have found a big benefit from keeping as many variables as possible as unsigned type, to avoid
sign conversion issues.

Best,
Aaron

**Comment by aous72** [comment]
Hi Aaron,

All is good; I hope the same for you.

I know there are a lot of warnings in clang.  Gcc seems to be happy.

I will get around to fix them in the coming few days.  My worry is introducing bugs in the process. 

Thanks for the advice on using unsigned types.  I think this is what I should do.

Kind regards,
Aous.

**Comment by boxerab** [comment]
I see you are working on removing these sign conversion warnings. Thank you!
I will close this.
