### ISSUE TITLE
Convert some asserts to runtime exceptions ?

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#43]
Hi Aous,
I hope all is well. I noticed that there are some assert statements in the block decoder and encoder.
As these get removed when building without debug symbols, do you think it is a good idea to convert
some of them to exceptions?  As the library gets used more in the wild. people will be throwing all sorts
of bad or malicious code streams at it - so, might be good to error out in these cases.
Thanks,
Aaron

**Comment by aous72** [comment]
Hi Aaron,

Thank you for asking.  I hope you are fine and doing well.  Thank you for closing the other issues.  Feel free to open them again if you feel the need.

I agree with you. For the decoder we certainly do, but the encoder is more under my control, and if I have no bugs, there should be no problem.

The issue for the decoder is that at some point, hopefully not far, I need to look at improving the speed of the decoder.  In this case, I need to rewrite the decoder in a way that makes it more amenable to SIMD implementation; the non-SIMD code should be directly translatable to SIMD code.  This allows me to test my SIMD code against non-SIMD code.  While I implement this, I should think deeply about what can possibly go wrong.

On another note, the packet header parser code can also benefit from checks against unreasonable values; for example, a codeblock that has too many bytes.  There might be other things to check.  

Keep this open until I settle these issues.

Kind regards,
Aous.

**Comment by boxerab** [comment]
Hi Aous,
All well here, thank you. 

And thanks for considering my idea, your plan sounds good to me. 
I'm very glad to hear you have plans to add a SIMD implementation, this should make the library even more
interesting for users. 

I agree with you. more sanity checks in the code stream parser are always good. 
As the standard is so complex, there are many opportunities for errors or hacked streams.

Best,
Aaron
