### ISSUE TITLE
decoder: handling scup == 0

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#46]
Hi Aous,

Does it make sense to reject code blocks with `scup` equal to 0 ?  

https://github.com/aous72/OpenJPH/blob/78c8a8026d3f717a13edec3e547f9a21c5b5fd3b/src/core/coding/ojph_block_decoder.cpp#L1022

i.e.  adding in:

```
if (scup == 0)
return false
```

`scup == 0` seems to indicate a corrupt code block

Thanks,
Aaron

**Comment by aous72** [comment]
Hi Aaron,

Thank you for this suggestion.  I will add it to the block decoder.

In fact, the standard says:
2 ≤ Scup ≤ min(Lcup, 4079)

Something like this can be used:
```
if (scup < 2 || scup > lcup || scup > 4079) //something is wrong
  return false;
```

Kind regards,
Aous.

**Comment by boxerab** [comment]
Great, thanks!
