### ISSUE TITLE
SIZ marker length errors

### ISSUE THREAD

**Issue by xinaesthete** [aous72/OpenJPH#57]
Greetings,

I'm using chafey's `openjphjs` library, with which I made a script to process a set of images and am now loading them for rendering, but the error appears to be at the level of this implementation.

I wrote a script to decode a set of images* with `openjpegwasm`, encode with `openjphjs` (with default parameters), and write the result to disk.

I then decode them with `openjphjs` for rendering, which mostly works fine (and faster than the old JPXs), but a few are triggering errors /warnings such as 
`ojph error 0x00050042 at ojph_params.cpp:552: error in SIZ marker length`
`ojph error 0x00050041 at ojph_params.cpp:548: error reading SIZ marker`
`ojph warning 0x00050001 at ojph_params.cpp:559: Rsiz in SIZ has unimplemented fields`
`ojph error 0x0005004E at ojph_params.cpp:588: Csiz does not match the SIZ marker size`
(that last error appearing after the warning)
`ojph error 0x00050044 at ojph_params.cpp:557: Rsiz bit 14 not set (this is not a JPH file)`
(perhaps it's true that none of them are proper JPH files, but most of them decode well enough for rock 'n' roll as far as I'm concerned, as per the readme `Adding the .jph header is of little urgency, as the codestream contains all needed information to properly decode an image`).

I'd be very happy to provide samples / reproduction. Perhaps it's best if I fork https://github.com/chafey/openjphjs with some samples that produce errors, as well as other similar files that do not (and in each case, the sources from which they are derived). It might also be worth me trying to use your own version of the WASM decoder and perhaps a different version of my encoding script also using your code more directly.

*16 bit unsigned grayscale JPX files originally produced using Pillow in Python, which I've previously been decoding with `openjpegwasm` for rendering in browser.

**Comment by aous72** [comment]
Hi Peter,

Thank you for the input.

This seems like a malformed header.
```ojph error 0x00050044 at ojph_params.cpp:557: Rsiz bit 14 not set (this is not a JPH file)```
means that the file is not a HTJ2K (i.e., not part 15 of the standard).

It is interesting to see the compressed file if you can just uploaded here.

Kind regards,
Aous.

**Comment by xinaesthete** [comment]
Thanks Aous,

I may as well just paste a few dropbox links.
[All of the bad files are here](https://www.dropbox.com/sh/0y5n5efxvnmjjbq/AAD9dh2ZwIM0KwXBNpUWeNBua?dl=0)
[Complete set of similar files, most of which appear ok](https://www.dropbox.com/sh/p6945c0ey76uzzd/AABXD-8TVCzoJgLtktUgpDLza?dl=0)
[Files from which these are derived](https://www.dropbox.com/sh/ipeqk3rd93lrfql/AACtPWUEoecbok1wovn8Xmnoa?dl=0)

**Comment by aous72** [comment]
Thank you uploading the files.

I had a look at a couple of them.

For the files I looked at, I noticed that the first 8 bytes are set to zero in the corrupt file.  
The following are the first 80 bytes from a correct file and a corrupt file. 
The first image taken from dtm_F0206052_20180201_20180202_mm_units.asc_normalised_60db.j2c
![dtm_F0206052_20180201_20180202_mm_units asc_normalised_60db](https://user-images.githubusercontent.com/7401883/107090099-cca6f480-6853-11eb-8a52-b7cc1525e3fe.png)
while the second is taken from dtm_F0206051_20180201_20180202_mm_units.asc_normalised_60db
![dtm_F0206051_20180201_20180202_mm_units asc_normalised_60db](https://user-images.githubusercontent.com/7401883/107090102-cf094e80-6853-11eb-9a12-f2e933273b21.png)

This is repeated in some other files.  Putting back the zeroed 8 bytes enabled me to correctly decode the corrupt file.  You can put back ```ff 4f ff 51 00 29 40 00``` I believe these should work for all the files that have the same problem.

As to the reason, I am not sure.  It is a problem with generating HTJ2K files.  It can be in my code (as an author I tend to think it is not, but I stand to be corrected).  It might have been in the juggling of the data within wasm or javascript.

As for the message we are currently getting.  OpenJPH searches for the start of the codestream (SOC), which has the sequence 0xFF 0x4F and finds later in the file, but it is not the correct data so you get all these error messages,

Hope this helps.

Kind regards,
Aous

**Comment by xinaesthete** [comment]
Thanks very much for your feedback Aous.

I've now tried re-coding the files with your CLI version (built with VS2019 as x64 Release, FWIW) and indeed do not reproduce the same problem - so that appears to support the hypothesis that the underlying error is not yours and it may be worth reporting on the other repo.

I do seem to be having another issue, seemingly unrelated -unless the real underlying issue turns out to be something like corruption in my file system...

Some files output by `ojph_compress` (with no arguments apart from -i and -o) are <1kb and producing an error `ojph error 0x00030051 at ojph_codestream.cpp:882: File ended before finding a tile segment` when decoded.

This should perhaps be posted as a separate issue - before I do that I'll try to see if I can reproduce the issue on another system to eliminate that as a variable.

I've put problematic `j2c`s along with correspnding `pgm`s from which they are derived in [another dropbox folder](https://www.dropbox.com/sh/474qb5mt7qm8pd0/AAC8CfSNo0iEtAHepN-qUnQ8a?dl=0). I glanced at a couple of the pgm headers and they seem ok, I haven't scrutinized more thoroughly than that.

Best wishes,
Peter

**Comment by aous72** [comment]
Hi Peter,
I had no internet at home today, so i will be short.
At face value, these short files are truncated files.
Truncated early due to some issue, for example there was not enough disk space. I cannot tell exactly what happened.
It would be great if you have a repeatable problem, but i am more inclined to think that the problem is not in the OpenJPH.

Thank you Peter.

Kimd regards,
Aous

**Comment by xinaesthete** [comment]
Indeed, the short files are derived repeatably from the corresponding `pgm`s here (but it may be worth me verifying that on another system).

e.g. `ojph_compress -i su3027_DSM_2M.asc_normalised_60db.pgm -o su3027_DSM_2M.asc_normalised_60db.j2c` resulted in the truncated file you see there.

**Comment by aous72** [comment]
Hi Peter,

Thank you for spotting this.

It is a bug in my code.  I have just pushed a new commit to master to address this issue.

It occurred because of the way I read ppm/pgm files.  I was using scanf to read width, height, and max_val, with '\n' at the end.  This '\n' makes scanf read potentially many whitespaces after max_val while the correct behavior is to read only one character.  This has changed now.

Kind regards,
Aous.

**Comment by xinaesthete** [comment]
Hi Aous,

That's great, I do indeed seem to be able to get a clean run of my dataset. Meant to comment before, just remembered.

Cheers,
Peter
