### ISSUE TITLE
codestream::check_boardcast_validity() typo

### ISSUE THREAD

**Issue by dtatut** [aous72/OpenJPH#61]
Minor typo, but this method, in ojph_codestream.cpp

codestream::check_boardcast_validity()

should really be named

codestream::check_broadcast_validity()

**Comment by aous72** [comment]
Hi Dan,

Thank you catching this.  I know it can get annoying after a while.

I fixed it.

Kind regards,
Aous

**Comment by aous72** [comment]
An old issue.
