### ISSUE TITLE
Support multiple cores

### ISSUE THREAD

**Issue by DAOCUONG** [aous72/OpenJPH#67]
Stress test the OpenJPH with  4 cores machine we see that the CPU usage is not equal for all cores one of core use 100% but other is just 30%

**Comment by chafey** [comment]
OpenJPH does not currently support multiple cores.  You can decode multiple images in parallel by running separate instances of OpenJPH in separate threads/web workers though.

**Comment by aous72** [comment]
Thank you Chris.

This is correct. OpenJPH supports one thread for the time being.  
Supporting multiple threads puts restrictions on the code.  
I think, it is better to optimize the block decoder/encoder using SIMD instructions.

**Comment by DAOCUONG** [comment]
Thanks you for the information
