### ISSUE TITLE
Lossless encode increase image size

### ISSUE THREAD

**Issue by ngoclinh93qt** [aous72/OpenJPH#68]
Hi,
I used the lib to encode my Jpeg, I parse the image to PPM format and encode but after encoded for the image I got the J2C image big than the Jpeg Image. my code, jpeg image below, I can send the j2c file if you need.
![parking](https://user-images.githubusercontent.com/55199882/133299599-4c5edda2-db6e-44a2-aee6-726b04a5ff08.jpg)
![Screen Shot 2021-09-14 at 23 37 29](https://user-images.githubusercontent.com/55199882/133299700-25df9e50-47b7-404d-a768-f0b92629cfd9.png)

**Comment by aous72** [comment]
Hi,

Sorry for the late reply; I had to go through some other stuff.

It is useful to address some background of what you are doing.
JPEG2000 is significantly different to JPEG, and therefore it is not possible to losslessly transcode (or convert) JPEG2000 to JPEG, or the other way.  The information stored in JPEG2000 (uses wavelet transform) is different to that stored in JPEG (uses the DCT). 
Lossless JPEG2000 or HTJ2K provides better quality than JPEG with QFactor of 1.  Therefore, you see this increase in size.

I would suggest to use lossless JPEG2000 only on images with very high quality (such as uncompressed original images).
For previously compressed images, such as the one you are providing, I would suggest using irreversible JPEG2000, "cod.reversible(false)" and then set the quantization step size to something like the one you have "codestream.access_qcd().set_irrev_quant(0.1);"
With this image, -qstep 0.03, the JPEG image and HTJ2K image look roughly the same. 
Values > 0.03 produces worst quality, and smaller values produces better quality.
Qstep should be 0.5 or smaller, and for 8 bit images, it not useful to be smaller than 1/256 = 0.0039.

Let me know if you need more info.

Cheers,
Aous

**Comment by ngoclinh93qt** [comment]
Thank you very much for the very useful information.
