### ISSUE TITLE
Error decode PPM

### ISSUE THREAD

**Issue by Jamaika1** [aous72/OpenJPH#70]
https://github.com/aous72/OpenJPH/commit/67fda0caf00bfb53a800ecfe4cdbd81fea8f740c
```
htj2k-cjph.exe -i image_21447_24bit.yuv -o image_21447_24bit-jph.j2c -dims {1563,1558} -num_comps 3 -signed false -bit_depth 10 -downsamp {1,1},{2,1},{2,1} -block_size {64,64} -precincts {128,128},{256,256} -prog_order CPRL -reversible true
```
```
htj2k-djph.exe -i image_21447_24bit-jph.j2c -o xxx.ppm
```
ojph error 0x20000003 at ojph_expand.cpp:235: To save an image to ppm, all the components must have the downsampling ratio
```
dopen_j2c.exe -i image_21447_24bit-jph.j2c -o xxx.ppm
```
[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.
[INFO] Generated Outfile xxx.ppm
decode time: 136 ms

**Comment by aous72** [comment]
Hi Lucas,

This images has two downsampled components.  The only way to save them to ppm is if you interpolate these two components.  Then, if you were to interpolate, where do these component sit relative to the first component (the one that is not downsampled); possible answers are: 0,0 or 1,1 or 0.5, 0.5 and many other locations.

We cannot expect a decoder to be able to do all possible imagined tasks.  For these tasks, you have to write your own code.

Kind regards,
Aous

**Comment by Jamaika1** [comment]
Hi Aous
Maybe I'm doing something wrong. What should be sampling for 4: 2: 2?
I'm just thinking. Since openjpeg allows 4: 2: 2 sampling. Maybe there's no blockage there.

**Comment by aous72** [comment]
You setting is correct. -downsamp {1,1},{2,1},{2,1}.
When YUV is used, OpenJPH store image components as images, no color transform is employed. Also, the .j2c file tells the decoder not use color transform.

I do not know what happens in OpenJPEG; when you save to ppm, II think the result would still be in YUV, not in RGB.
Also not sure if the up-sampling is correct.

**Comment by Jamaika1** [comment]
```
When YUV is used, OpenJPH store image components as images, no color transform is employed. Also, the .j2c file tells the decoder not use color transform.
```
OK. And it generally keeps some subsamling data. For RGB24 I have red photos when decoding.

**Comment by aous72** [comment]
It keeps the sub-sampling data. Like you discovered, it does not perform color transform.

**Comment by Jamaika1** [comment]
OK. Right. There is no info. I should only decode to PPM.

**Comment by aous72** [comment]
If you encode ppm, decode to ppm.  If you encode yuv, decode to yuv.
