### ISSUE TITLE
Possible bug in codeblock::gen_find_max_val()

### ISSUE THREAD

**Issue by chafey** [aous72/OpenJPH#92]
Was reviewing the code and noticed that the general (non SIMD) version of find_max_val() simply returns the first uint32 in the array while the SIMD accelerated versions use the first 8 bytes.  

General:
https://github.com/aous72/OpenJPH/blob/master/src/core/codestream/ojph_codestream_local.h#L407

SSE2:
https://github.com/aous72/OpenJPH/blob/master/src/core/codestream/ojph_codestream_sse2.cpp#L45

This seems suspicious to me - is the general version incomplete or are we doing unnecessary work in the SIMD versions?  Or am I missing something?

**Comment by aous72** [comment]
Hi Chris

After two weeks of health issues, I was admitted to hospital 8 days ago. Not clear when I will be discharged. I hope end of the week or next week.

This is my recollection.

The scalar version uses one accumulator (4 bytes), which can be used directly.

The SIMD version uses 4 4-byte accumulators (for SSE2) and 8 (for AVX2). Before using accumulated data, we need to combine the accumulators, using SIMD code. The last two elements are extracted and combined.

Hope this is useful.

Kind regards,
Aous

**Comment by chafey** [comment]
Yikes - sorry to hear that!  Hope you get well soon!  Good to know this isn't a bug, I'll dig deeper into this and add some comments to my refactor branch
